# Generated by Django 2.0.2 on 2018-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='song title')),
                ('artist', models.TextField(verbose_name='artist')),
                ('lyricist', models.TextField(verbose_name='lyricist')),
                ('composer', models.TextField(verbose_name='composer')),
                ('arranger', models.TextField(verbose_name='arranger')),
                ('release_date', models.DateTimeField(verbose_name='date of song release')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('kanji', models.TextField(verbose_name='kanji lyrics')),
                ('romaji', models.TextField(verbose_name='romaji lyrics')),
                ('english', models.TextField(verbose_name='english lyrics')),
            ],
        ),
    ]
