# Generated by Django 2.0.2 on 2018-03-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.TextField(verbose_name='kanji name')),
                ('romaji', models.TextField(verbose_name='romaji name')),
                ('english', models.TextField(verbose_name='english name')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kanji', models.TextField(verbose_name='song title in kanji')),
                ('title_romaji', models.TextField(verbose_name='song title in romaji')),
                ('title_english', models.TextField(verbose_name='song title in english')),
                ('lyricist', models.TextField(verbose_name='lyricist')),
                ('composer', models.TextField(verbose_name='composer')),
                ('arranger', models.TextField(verbose_name='arranger')),
                ('release_date', models.DateTimeField(verbose_name='date of song release')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('kanji', models.TextField(verbose_name='kanji lyrics')),
                ('romaji', models.TextField(verbose_name='romaji lyrics')),
                ('english', models.TextField(verbose_name='english lyrics')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.Artist')),
            ],
        ),
        migrations.DeleteModel(
            name='Lyrics',
        ),
    ]
